version: '3.5'
services:
  terminalserver:
    build: ./
    image: ghcr.io/drerik/xrdp-xfce4:main
    container_name: uxrdp
    hostname: terminalserver
    restart: always
    shm_size: 1g
    environment:
       IDLETIME: 11
    ports:
      - "3389:3389"
      - "2222:22"
    volumes:
      - ssh:/etc/ssh/
      - home:/home/
      - $PWD/users.list.example:/etc/users.list

volumes:
  ssh:
  home:
