version: '3.5'
services:
  terminalserver:
    #build: ./
    image: ghcr.io/drerik/xrdp-xfce4-no:main
    hostname: terminalserver
    restart: always
    shm_size: 1g
    environment:
       IDLETIME: 11
    ports:
      - "3389:3389"
      - "2222:22"
    volumes:
      - ssh:/etc/ssh/
      - home:/home/
      - $PWD/etc/users.list:/etc/users.list:ro

volumes:
  ssh:
  home:
